printWidth: 120
tabWidth: 4
useTabs: false
semi: true
singleQuote: true
quoteProps: 'consistent'
jsxSingleQuote: true
trailingComma: 'es5'
bracketSpacing: true
bracketSameLine: true
arrowParens: 'always'
requirePragma: false
insertPragma: false
proseWrap: 'always'
htmlWhitespaceSensitivity: 'css'
vueIndentScriptAndStyle: true
endOfLine: 'lf'
